graphql:
  servers-by-methods:
    filter: grpc-server
    getById: grpc-server
    update: grpc-server
grpc:
  servers:
    grpc-server:
      service-name: "ru.craftysoft.platform.grpcservice.proto.GrpcService"
      host: 0.0.0.0
      port: 9000
      reflection-client-deadline: 1000
      dynamic-client-deadline: 2000
quarkus:
  log:
    level: INFO
    category:
      "ru.craftysoft":
        min-level: TRACE
        level: TRACE