graphql:
  services-by-methods:
    filter: grpc-service
    getById: grpc-service
    update: grpc-service
    empty: grpc-service
grpc:
  services:
    grpc-service:
      service-name: "ru.craftysoft.platform.grpcservice.proto.GrpcService"
      host: 0.0.0.0
      port: 9000
      reflection-client-deadline: 1000
      dynamic-client-deadline: 2000
quarkus:
  cache:
    caffeine:
      server-reflection-info:
        expire-after-write: 60S
        maximum-size: 100
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %X %s%e%n"
    category:
      "ru.craftysoft":
        min-level: TRACE
        level: TRACE