graphql:
  services-by-methods:
    documentFilter: document-service
    attributeFilter: attribute-service

grpc:
  services:
    document-service:
      service-name: "ru.craftysoft.platform.grpcservice.proto.DocumentService"
      host: 0.0.0.0
      port: 9000
      reflection-client-deadline: 1000
      dynamic-client-deadline: 2000
    attribute-service:
      service-name: "ru.craftysoft.platform.grpcservice.proto.AttributeService"
      host: 0.0.0.0
      port: 9000
      reflection-client-deadline: 1000
      dynamic-client-deadline: 2000

nadel:
  graphql-contracts-by-services:
    attribute-service: attribute-service.graphqls
    document-service: document-service.graphqls
  nadel-contracts-by-services:
    attribute-service: attribute-service.graphqls
    document-service: document-nadel-service.graphqls

quarkus:
  cache:
    caffeine:
      server-reflection-info:
        expire-after-write: 60S
        maximum-size: 100
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %X %s%e%n"
    category:
      "ru.craftysoft":
        min-level: TRACE
        level: TRACE